### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by AntouanK** [arzzen/curltime#1]
I get this error when I try it ( same with any URL I try )

<img width="716" alt="screen shot 2016-03-11 at 15 06 23" src="https://cloud.githubusercontent.com/assets/4569111/13705941/fcd1ff18-e79a-11e5-9407-25baaabf83e8.png">

**Comment by arzzen** [comment]
This is because you are using `sh` in your script, as a fix you should change it to `bash`.

**Comment by AntouanK** [comment]
You're right.
I made it an executable and it works, thanks.
